import type { Contact, RelatedContact, OwnedProperty, ActivityItem } from "./types";

export const MOCK_CONTACTS: Contact[] = [
  {
    id: "1",
    type: "company",
    name: "Inversiones Costa del Sol S.L.",
    comercialName: "Costa Invest",
    cifNif: "B29456781",
    emails: ["info@costainvest.es", "admin@costainvest.es"],
    phones: ["+34 952 123 456", "+34 600 111 222"],
    web: "www.costainvest.es",
    address: "Av. Ricardo Soriano 72, 29601 Marbella",
    roles: ["client", "owner"],
    status: "active",
    languages: ["ES", "EN"],
    origin: "referral",
    notes: "Interesado en propiedades premium zona golden mile.",
    paymentDays: 30,
    iban: "ES12 3456 7890 1234 5678 9012",
    currency: "EUR",
  },
  {
    id: "2",
    type: "person",
    name: "María García López",
    firstName: "María",
    lastName: "García López",
    cifNif: "12345678A",
    emails: ["maria.garcia@email.com"],
    phones: ["+34 611 222 333"],
    address: "C/ Gran Vía 45, 3ºB, 28013 Madrid",
    roles: ["client"],
    status: "active",
    languages: ["ES", "EN", "FR"],
    origin: "web",
    notes: "Busca piso en Madrid centro, presupuesto 400-600k.",
  },
  {
    id: "3",
    type: "person",
    name: "James Wilson",
    firstName: "James",
    lastName: "Wilson",
    cifNif: "X1234567B",
    emails: ["james.wilson@gmail.com", "j.wilson@corp.co.uk"],
    phones: ["+44 7700 900123"],
    address: "Urb. Los Monteros, 29603 Marbella",
    roles: ["owner"],
    status: "active",
    languages: ["EN"],
    origin: "event",
  },
  {
    id: "4",
    type: "company",
    name: "Reformas Mediterráneo S.A.",
    comercialName: "ReforMed",
    cifNif: "A41987654",
    emails: ["contacto@reformed.es"],
    phones: ["+34 955 678 901"],
    address: "Pol. Ind. El Pino, Nave 12, Sevilla",
    roles: ["provider"],
    status: "active",
    languages: ["ES"],
    origin: "cold-call",
    paymentDays: 60,
  },
  {
    id: "5",
    type: "person",
    name: "Ana Martínez Ruiz",
    firstName: "Ana",
    lastName: "Martínez Ruiz",
    cifNif: "87654321C",
    emails: ["ana.martinez@inmobiliaria.es"],
    phones: ["+34 622 333 444"],
    roles: ["worker"],
    status: "active",
    languages: ["ES", "EN"],
    origin: "referral",
  },
  {
    id: "6",
    type: "company",
    name: "Nordic Homes AB",
    comercialName: "Nordic Homes",
    cifNif: "SE556677-8899",
    emails: ["info@nordichomes.se"],
    phones: ["+46 8 123 456"],
    roles: ["client"],
    status: "provisional",
    languages: ["EN", "DE"],
    origin: "portal",
  },
  {
    id: "7",
    type: "person",
    name: "Carlos Fernández Díaz",
    firstName: "Carlos",
    lastName: "Fernández Díaz",
    cifNif: "45678901D",
    emails: ["carlos.fd@outlook.es"],
    phones: ["+34 633 444 555"],
    address: "Paseo de la Castellana 120, Madrid",
    roles: ["client", "owner"],
    status: "active",
    languages: ["ES"],
    origin: "web",
  },
  {
    id: "8",
    type: "person",
    name: "Sophie Dubois",
    firstName: "Sophie",
    lastName: "Dubois",
    cifNif: "Y9876543E",
    emails: ["sophie.dubois@free.fr"],
    phones: ["+33 6 12 34 56 78"],
    roles: ["client"],
    status: "archived",
    languages: ["FR", "EN", "ES"],
    origin: "event",
  },
  {
    id: "9",
    type: "company",
    name: "Electricidad Torres e Hijos S.L.",
    cifNif: "B12345678",
    emails: ["torres@electricidad.es"],
    phones: ["+34 951 234 567"],
    roles: ["provider"],
    status: "active",
    languages: ["ES"],
    origin: "cold-call",
    paymentDays: 45,
  },
  {
    id: "10",
    type: "person",
    name: "Dmitry Volkov",
    firstName: "Dmitry",
    lastName: "Volkov",
    cifNif: "Z1122334F",
    emails: ["dmitry@volkov.ru"],
    phones: ["+7 916 123 4567"],
    roles: ["client", "owner"],
    status: "provisional",
    languages: ["RU", "EN"],
    origin: "referral",
  },
];

export const MOCK_RELATED_CONTACTS: RelatedContact[] = [
  { contactId: "2", name: "María García López", relationship: "associate" },
  { contactId: "5", name: "Ana Martínez Ruiz", relationship: "employee" },
];

export const MOCK_OWNED_PROPERTIES: OwnedProperty[] = [
  { id: "p1", title: "Villa Panoramic Sea Views", reference: "REF-2024-001", status: "En venta" },
  { id: "p2", title: "Ático Duplex Golden Mile", reference: "REF-2024-015", status: "Reservado" },
];

export const MOCK_ACTIVITIES: ActivityItem[] = [
  { id: "a1", date: "2026-02-24", description: "Llamada de seguimiento sobre Villa Panoramic", type: "call" },
  { id: "a2", date: "2026-02-22", description: "Envío de documentación fiscal", type: "email" },
  { id: "a3", date: "2026-02-20", description: "Visita al Ático Duplex Golden Mile", type: "visit" },
  { id: "a4", date: "2026-02-18", description: "Nota: Solicita valoración de su chalet en Estepona", type: "note" },
  { id: "a5", date: "2026-02-15", description: "Contrato de arras firmado", type: "document" },
];
